### ISSUE TITLE
connectivity: proposal for degraded connectivity behavior

### ISSUE THREAD

**Issue by junr03** [lyft/envoy-mobile#10]
Design an API for envoy to be aware of OS level signals (e.g connection to WiFi vs mobile network, app backgrounded) in order for envoy to react appropriately.

**Comment by costinm** [comment]
+1 - include battery info as well if possible. All this would be very valuable on the control plane - 
based on network type (metered, speed) and battery status it can push different configs.

As a proposal,  a method "setMetadata" to update the bootstrap node.metadata, so the management
server can make decisions based on the current information. The method would just update the meta and do some update on the XDS to make sure the server gets the new status.

Technically it is possible to restart envoy with a different bootstrap config whenever the network or battery config changes. 

Note that net config changes also result in new interfaces and IPs that envoy might need to bind to.

**Comment by junr03** [comment]
Done in https://github.com/lyft/envoy-mobile/pull/442.
