### ISSUE TITLE
crash: static destruction leads to unavailable mutex

### ISSUE THREAD

**Issue by junr03** [lyft/envoy-mobile#1035]
std::__1::system_error: mutex lock failed: Invalid argument

0  libsystem_kernel.dylib  ___ulock_wait
1  libsystem_pthread.dylib __pthread_join
2  libc++.1.dylib          std::__1::thread::join()
3  Lyft                    Envoy::Engine::~Engine() (Lyft)
4  Lyft                    std::__1::shared_ptr<unsigned int>::~shared_ptr() (Lyft)
5  libsystem_c.dylib       ___cxa_finalize_ranges
6  libsystem_c.dylib       _exit
7  UIKitCore               -[UIApplication _terminateWithStatus:]
8  UIKitCore               -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]
9  UIKitCore               -[_UISceneLifecycleMultiplexer forceExitWithTransitionContext:scene:]
10 UIKitCore               -[UIApplication workspaceShouldExit:withTransitionContext:]
11 FrontBoardServices      -[FBSUIApplicationWorkspaceShim workspaceShouldExit:withTransitionContext:]
12 FrontBoardServices      ___83-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:withAcknowledgement:]_block_invoke_2
13 FrontBoardServices      -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:]
14 FrontBoardServices      ___83-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:withAcknowledgement:]_block_invoke
15 libdispatch.dylib       __dispatch_client_callout
16 libdispatch.dylib       __dispatch_block_invoke_direct
17 FrontBoardServices      __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
18 FrontBoardServices      -[FBSSerialQueue _queue_performNextIfPossible]
19 FrontBoardServices      -[FBSSerialQueue _performNextFromRunLoopSource]
20 CoreFoundation          ___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
21 CoreFoundation          ___CFRunLoopDoSource0
22 CoreFoundation          ___CFRunLoopDoSources0
23 CoreFoundation          ___CFRunLoopRun
24 CoreFoundation          _CFRunLoopRunSpecific
25 GraphicsServices        _GSEventRunModal
26 UIKitCore               _UIApplicationMain
27 Lyft                    main (Lyft)
28 libdyld.dylib           _start

**Comment by rebello95** [comment]
@junr03 was this fixed by https://github.com/lyft/envoy-mobile/pull/1021?

**Comment by junr03** [comment]
Up for confirmation. Will close if that is the case.
