### ISSUE TITLE
[ANDR] Make StatsClient protocol's method return Counter protocol

### ISSUE THREAD

**Issue by Augustyniak** [lyft/envoy-mobile#1053]
Android only: The public interface of `StatsClient` returns a Counter object. Make it return a `Counter` protocol instead and move the current implementation to `CounterImpl` class that conforms to `Counter` protocol. The similar change was implemented on iOS as part of https://github.com/lyft/envoy-mobile/pull/1052.

**Comment by rebello95** [comment]
Done in https://github.com/lyft/envoy-mobile/pull/1058
// @Augustyniak @goaway
