### ISSUE TITLE
android: Battery/CPU usage audit

### ISSUE THREAD

**Issue by rebello95** [lyft/envoy-mobile#114]
- Analyze how Envoy Mobile affects battery usage on both iOS/Android while running and determine if this is a notable/concerning change that needs to be investigated further
- Note: @mattklein123 is familiar with configs that we can disable (such as DNS polling). Sync with him prior to starting the investigation. @Reflejo also has some ideas for battery auditing
- Audit CPU usage as well

**Document reference [here](https://docs.google.com/document/d/1eLbJEXog2Rn7wTBEbDIjpDV7dHecV_DV_dw8P5ZgbL4/edit#heading=h.occj97i4e2ai).**
iOS issue: https://github.com/lyft/envoy-mobile/issues/113

**Comment by buildbreaker** [comment]
Taking some stabs for battery profiling here using: https://github.com/google/battery-historian

**Comment by buildbreaker** [comment]
Planning to use the battery-historian tool. There's row called `Device estimated power use` and `CPU system time` which sounds like what we want for the battery and CPU usage analysis.

The set up will be that we will run two applications:
1. Hello Envoy Kotlin (the demo application within our repository
2. Modified Hello Envoy Kotlin (removing all Envoy references and hitting s3 directly)

Steps:
1. Unplug the device
1. Open both applications
1. Run the clear battery history
1. Wait an hour (or whatever interval)
1. Dump results and analyze

I'll first run this for an hour and see what information we get and we can run a longer term version after.

**Comment by buildbreaker** [comment]
For completeness, this is the branch I'm using: https://github.com/lyft/envoy-mobile/pull/159

To install the applications:
Envoy: `bazel mobile-install //examples/kotlin/hello_world:hello_envoy_kt --fat_apk_cpu=armeabi-v7a` 
Control: `bazel mobile-install //examples/control/hello_world:hello_control_kt`

**Comment by buildbreaker** [comment]
I can run this a few more times but here's the results so far for the control application (Duration is ran for ~1hr)

| CONTROL 1 |  |
| ----------  | ---------- |
| Device estimated power use | 5.45% |
| Duration | 51m 33s 491ms |
| CPU user time | 3m 10s 44ms |
| CPU system time | 54s 519ms |

| CONTROL 2 |  |
| ----------  | ---------- |
| Device estimated power use | 5.88% |
| Duration | 1h 2m 0s 223ms|
| CPU user time | 3m 37s 880ms |
| CPU system time | 1m 1s 720ms |

**Comment by buildbreaker** [comment]
Results for Envoy (Run for ~30minutes):

| ENVOY 1 |  |
| ----------  | ---------- |
| Device estimated power use | 7.02% |
| Duration | 31m 0s 268ms |
| CPU user time | 5m 51s 673ms |
| CPU system time | 1m 50s 439ms |

**Comment by buildbreaker** [comment]
Having some issues with using the [`Profiler`](https://developer.android.com/studio/profile/cpu-profiler) plugin on Android Studio. I'm getting unexpected results where the Envoy performs similarly to the control.
Control
<img width="1685" alt="control" src="https://user-images.githubusercontent.com/7771562/60220819-3b287180-982c-11e9-8ff1-2281bf739374.png">

Envoy
<img width="1683" alt="envoy" src="https://user-images.githubusercontent.com/7771562/60220893-68751f80-982c-11e9-8083-bb10c6f3ec8f.png">

**Comment by buildbreaker** [comment]
There's a [suggestion](https://stackoverflow.com/questions/14042687/cpu-usage-per-application-in-android) that we could use `adb shell top` to look at the memory/cpu usage. I just used `adb shell top -m 10 | grep envoy` and took the average and variance of the reported `%cpu` and `%mem`:

| Envoy | AVG | VAR |
| -- | --: | --: |
| `%MEM` | 2.695238095 | 0.0004608294931 |
| `%CPU` | 9.307936508 | 26.3481618 |

| Control | AVG | VAR |
| -- | --: | --: |
| `%MEM` | 1.964935065 | 0.002570061517 |
| `%CPU` | 4.348051948 | 26.55700273 |

Interesting bits are from the earlier parts of the applications which I assume relates to when envoy is started:

| Envoy | AVG |
| -- | --: |
| `%MEM` |  2.672727273 |
| `%CPU` | 15.70909091 |

| Control | AVG |
| -- | --: |
| `%MEM` | 1.890909091 |
| `%CPU` | 13.19090909 |

**Comment by buildbreaker** [comment]
From this preliminary investigation so far, it looks like the following:
1. Envoy's CPU consumption is ~2 times more than the control (~0.23%/min v ~0.11%/min)
1. Envoy's battery consumption is ~times more than the control (avg ~9.3% vs ~4.3%)

Battery analysis:
1. Kill all apps on the phone
1. Unplug the phone
1. Run the application (I just let the application run until my phone sleeps)
1. Export the report from the phone
1. Use [`battery-historian`](https://github.com/google/battery-historian) to identify the battery usage and application up time

CPU analysis:
1. Kill all apps on the phone
1. run `adb shell top -m 10 | grep envoy`
1. Run the application (I just run until my terminal is full)
1. Take the first N data for averaging

**Comment by buildbreaker** [comment]
# CPU memory usage with the cache disabled

1. CPU usage is around ~40% more on Envoy than the control (~15% versus ~11%)
1. Memory usage is around ~25% more on Envoy than the control (~2.7% versus ~2.2%)


| [Envoy](https://github.com/lyft/envoy-mobile/files/3337051/envoy.txt) | AVG | VAR |
| -- | --: | --: |
| `%MEM` | 2.696341463 | 0.02603583258 |
| `%CPU` | 15.67560976 | 10.04803975 |

| [Control](https://github.com/lyft/envoy-mobile/files/3337050/control.txt) | AVG | VAR |
| -- | --: | --: |
| `%MEM` | 2.152439024 | 0.002771755495 |
| `%CPU` | 11.27439024 | 7.760940982 |

Interesting bits are from the earlier parts of the applications which I assume relates to when envoy is started:

| Envoy | AVG |
| -- | --: |
| `%MEM` |  2.554545455 |
| `%CPU` | 20.87272727 |

| Control | AVG |
| -- | --: |
| `%MEM` | 2.090909091 |
| `%CPU` | 15.88181818 |

**Comment by buildbreaker** [comment]
Created documentation here: https://github.com/lyft/envoy-mobile/pull/210
