### ISSUE TITLE
android: Unary HTTP request interfaces

### ISSUE THREAD

**Issue by rebello95** [lyft/envoy-mobile#119]
- Utilize the common request interfaces and wrap them in native Swift/Kotlin code for end consumers to use for performing unary HTTP requests
- This is the bulk of the work required for performing HTTP requests directly through Envoy Mobile

**Detailed documentation on what these interfaces should look like is available in [this doc](https://docs.google.com/document/d/1N0ZFJktK8m01uqqgfDRVB9mpC1iEn9dqkQaa_yMn_kE/edit#heading=h.i6ky65xaa9va).**
iOS issue: https://github.com/lyft/envoy-mobile/issues/118

**Comment by buildbreaker** [comment]
https://github.com/lyft/envoy-mobile/pull/240

**Comment by buildbreaker** [comment]
responses: https://github.com/lyft/envoy-mobile/pull/260

**Comment by rebello95** [comment]
New responses PR: https://github.com/lyft/envoy-mobile/pull/265

**Comment by rebello95** [comment]
This is actually complete on master.
