### ISSUE TITLE
common: http request interface

### ISSUE THREAD

**Issue by goaway** [lyft/envoy-mobile#167]
Build out the interface that will be leveraged by the platform-specific stack to issue HTTP requests and receive responses. This will be informed by Envoy's internal API, and use this spec as a starting point:

https://docs.google.com/document/d/1N0ZFJktK8m01uqqgfDRVB9mpC1iEn9dqkQaa_yMn_kE/edit#heading=h.i6ky65xaa9va

**Comment by junr03** [comment]
This has been implemented for both platforms. The demos are currently built using the implemented interfaces.
