### ISSUE TITLE
reduce binary size

### ISSUE THREAD

**Issue by junr03** [lyft/envoy-mobile#17]
In order for us to be able to ship Envoy on the client we need to optimize for binary size. 

We will need to reduce Envoy Mobile’s final application bloat (compressed) down to < 5MB to be able to ship in a production mobile application

**Comment by junr03** [comment]
I picked up where @tonya11en left off.

I ran the same binary he was creating with a custom bloaty data source:

```
custom_data_source: {
  name: "bloaty_package"
  base_data_source: "compileunits"

  rewrite: {
    pattern: "^(external/envoy/source/)(\\w+/)(\\w+)"
    replacement: "envoy \\2"
  }

  rewrite: {
      pattern: "^(external/)(\\w+/)"
      replacement: "\\2"
  }

  rewrite: {
      pattern: "([.pb.cc | .pb.validate.cc])$"
      replacement: "compiled protos"
  }
}
```

This starts allowing us to aggregate size by files.

Results:  [test_initial_06_19.txt](https://github.com/lyft/envoy-mobile/files/3307601/test_initial_06_19.txt)

Interesting observations:

1.  boringssl and protobuf take up -- together - ~3.5mi so even when we squeeze what we can out of the envoy codebase this will be a determining factor for the size. I discussed with @goaway, and we might want to look at possibilities for dynamically linking to the version compiled into the parent app. More discussion is needed in this point.
2.  The largest culprit of size are the compiled protos. Both the normal ones and the .validate ones generated by protoc-gen-validate. Most of these protos are not needed. I had thought that they would be compiled out if they were not included by any of the source files used. Good avenue for exploration.
3.  As far as I can see, only the necessary extensions are getting compiled in, so that is good.
4. Note that the exception table is a non-negligible amount. However, this is not representative of what we are going to put in the app given that I did not compile against arm. I will do that to get and actual sense for the real exception table size.

Next steps:

1. Looking into compiling out logging. I will hack something quick, get data, and then work to upstream.
2. Look into the protos
3. compile against arm.

**Comment by junr03** [comment]
### 06/20 update

#### What was done

1.  I would have liked to compile just the c++ code with arm64 as a target architecture. However, based on my own research, my reaching out to several members of the envoy community, and talking to @keith, building that kind of cross compile support is "where dragins lie". I might try compiling natively at some point, just not now.
2.  Given `1` I moved on to compiling the artifacts for ios and android given that those rules already have cross compilation toolchains available to them. I will break down what I did in each platform.

##### iOS

I built the Envoy.framework with the following command:
`bazel build //:ios_dist --config=ios -c dbg --strip=never --ios_multi_cpus=arm64` 

Using this I can get size information of the composing object files with 

```
mkdir /tmp/foo
cd /tmp/foo
ar x path/to/Envoy.framework
du -sh * | gsort -h
```

However, when I tried to get symbols from the object files I was not able to do so. e.g:

```
12:29:45  /tmp/dbg_framework $ bloaty -d compileunits listener_manager_impl.o
bloaty: missing debug info
12:30:00  /tmp/dbg_framework $ dsymutil listener_manager_impl.o
warning: no debug symbols in executable (-arch x86_64)
```
although as far as I can tell the object file does have debug symbols:

```12:29:37  /tmp/dbg_framework $ bloaty listener_manager_impl.o
    FILE SIZE        VM SIZE
 --------------  --------------
  44.0%  14.1Mi  45.6%  14.1Mi ,__debug_str
  24.6%  7.87Mi  25.5%  7.87Mi ,__debug_pubtypes
  20.8%  6.66Mi  21.6%  6.66Mi ,__debug_pubnames
   4.2%  1.35Mi   4.4%  1.35Mi ,__debug_info
   2.5%   834Ki   0.0%       0 String Table
   1.2%   393Ki   1.2%   393Ki ,__text
   0.6%   196Ki   0.6%   196Ki ,__eh_frame
   0.6%   182Ki   0.0%       0 [Unmapped]
   0.5%   177Ki   0.6%   177Ki ,__debug_line
   0.5%   155Ki   0.5%   155Ki ,__compact_unwind
   0.3%  87.7Ki   0.0%       0 Symbol Table
   0.0%  13.0Ki   0.0%  13.0Ki ,__const
   0.0%  7.88Ki   0.0%  7.88Ki ,__gcc_except_tab
   0.0%  7.12Ki   0.0%  7.12Ki ,__cstring
   0.0%  4.98Ki   0.0%  4.98Ki ,__debug_ranges
   0.0%  4.70Ki   0.0%  4.70Ki ,__debug_abbrev
   0.0%  2.19Ki   0.0%       0 [Mach-O Headers]
   0.0%  1.56Ki   0.0%  1.56Ki ,__debug_loc
   0.0%     289   0.0%     279 [10 Others]
   0.0%     288   0.0%     288 ,__StaticInit
   0.0%       0   0.0%     136 ,__bss
 100.0%  32.0Mi 100.0%  30.9Mi TOTAL```

At this point I stopped working on iOS as having the debug symbols is important to actually see what is going on.

@keith did mention I could try using `--apple_generate_dsym`. I will try that tomorrow.

###### Open questions:

1.  Can I get debug symbols?
2.  Can I get bloat information for the entirety of the library rather than per .o file?

##### Android

I moved on to android where I built the envoy.aar with `bazel build //:android_dist --fat_apk_cpu=arm64-v8a --strip=never -c dbg` and extracted the `libenvoy_jni.so` file. I was able to use all of bloaty's features.

I also created an optimized stripped envoy.aar with `bazel build //:android_dist ---fat_apk_cpu=arm64-v8a --strip=never -c opt`

The bloaty output is:
```
junr03@thinkpad:~/Desktop$ bloaty opt_stripped.so 
    FILE SIZE        VM SIZE    
 --------------  -------------- 
  29.8%  8.71Mi  41.9%  8.71Mi .text
  18.7%  5.47Mi   0.0%       0 .strtab
  14.6%  4.26Mi  20.5%  4.26Mi .dynstr
  10.3%  3.01Mi   0.0%       0 .symtab
   4.5%  1.33Mi   6.4%  1.33Mi .rela.dyn
   4.5%  1.31Mi   6.3%  1.31Mi .eh_frame
   4.0%  1.17Mi   5.6%  1.17Mi .dynsym
   3.6%  1.04Mi   5.0%  1.04Mi .rodata
   2.0%   587Ki   2.8%   587Ki .gcc_except_table
   1.6%   470Ki   2.2%   470Ki .data.rel.ro
   1.3%   399Ki   1.9%   399Ki .hash
   1.3%   376Ki   1.8%   376Ki .gnu.hash
   1.1%   328Ki   1.5%   328Ki .eh_frame_hdr
   0.9%   276Ki   1.3%   276Ki .rela.plt
   0.6%   184Ki   0.9%   184Ki .plt
   0.3%  99.8Ki   0.5%  99.8Ki .gnu.version
   0.0%       0   0.4%  92.2Ki .bss
   0.3%  92.1Ki   0.4%  92.1Ki .got.plt
   0.3%  83.8Ki   0.4%  81.3Ki [13 Others]
   0.1%  37.3Ki   0.3%  61.0Ki [LOAD #3 [RW]]
   0.2%  57.7Ki   0.0%       0 [Unmapped]
 100.0%  29.2Mi 100.0%  20.8Mi TOTAL
```
Given that baseline I went in an deleted all logging (with ifdefs, and commenting some stuff out). The diff between libenvoy_jni.so was:

```
junr03@thinkpad:~/Desktop$ bloaty no_log.so -- opt_orig.so 
    FILE SIZE        VM SIZE    
 --------------  -------------- 
   +71% +40.9Ki  [ = ]       0 [Unmapped]
  +2.5%    +952  +5.1% +3.12Ki [LOAD #3 [RW]]
  -0.5%    -272  -0.5%    -272 .got
  -0.4%    -376  -0.4%    -376 .gnu.version
  -0.0%    -224  -0.1%    -416 [5 Others]
  -0.2%    -940  -0.2%    -940 .gnu.hash
  -3.5%    -952  -3.5%    -952 .data
  -0.4% -1.23Ki  -0.4% -1.23Ki .eh_frame_hdr
  -0.4% -1.47Ki  -0.4% -1.47Ki .hash
  -1.9% -1.75Ki  -1.9% -1.75Ki .got.plt
  -1.9% -3.50Ki  -1.9% -3.50Ki .plt
  -0.3% -3.82Ki  -0.3% -3.82Ki .rela.dyn
  -0.4% -4.41Ki  -0.4% -4.41Ki .dynsym
  -1.9% -5.25Ki  -1.9% -5.25Ki .rela.plt
  -0.8% -10.2Ki  -0.8% -10.2Ki .eh_frame
  -0.5% -22.4Ki  -0.5% -22.4Ki .dynstr
  -0.4% -23.0Ki  [ = ]       0 .strtab
  -6.4% -68.2Ki  -6.4% -68.2Ki .rodata
  -2.4% -73.1Ki  [ = ]       0 .symtab
 -19.7%  -115Ki -19.7%  -115Ki .gcc_except_table
  -2.8%  -251Ki  -2.8%  -251Ki .text
  -1.8%  -546Ki  -2.3%  -489Ki TOTAL
```

###### Open Questions:

1.  I can't stamp the libenvoy_jni.so file, because if I understand correctly one can only stamp binaries and not object files. However, the lack of the stamp makes it so that bloaty does not allow me to extract debug symbols from the dbg .so and map them to the opt .so

**Comment by junr03** [comment]
@keith @Reflejo @mattklein123 @goaway  let me know what you think of the progress above. Also please comment if you have other ideas at pieces of data to look at, or next steps to take. This is the first time I am running an investigation of this sort (beyond very small toy projects), so your prior expertise is very valuable.

At this point I think that using the Android data compiled against arm, (albeit we have symbol resolution only in the -c dbg output), we probably have to make some calls about larger parts of envoy we can start compiling out.

**Comment by Reflejo** [comment]
@junr03 A few quick observations:

- I don't think compiling the framework is going to be valuable for this analysis. I didn't try it but I assume that static library size is in the order of 1Gb and it's not very meaningful since it has effectively no code stripping at all

- One thing I did try is to just get that `test_binary` linked and it's around 19M. One thing you can try is to pass `-Wl,-dead_strip` to the linker (you can get the original linker command by removing the binary and running bazel with `-s`); that will reduce the size to 13M (.

- The compressed size of that stripped binary (x86_64 btw) is 3.4M

- Didn't do any deep analysis but just quickly checking __cstring, there is a bunch of json stuff, coming from, for example [here](https://github.com/envoyproxy/envoy/blob/master/source/common/json/config_schemas.cc) and of course all assertion strings:

```bash
$ otool -l bazel-out/darwin-fastbuild/bin/library/common/test_binary.dead
Section
  sectname __cstring
   segname __TEXT
      addr 0x00000001004bf0a0
      size 0x0000000000048f45
    offset 4976800
     align 2^4 (16)
(...)
$ dd if=bazel-out/darwin-fastbuild/bin/library/common/test_binary.dead bs=1 skip=4976800 count=`rax2 0x48f45` of=whatev
```

this is not a _big_ deal because deflate compression on this section will be fairly effective. But this is obviously a low hanging fruit I think there are ~300K of these (on my stripped version of the binary). 

- On the stripped binary theere are also at least 1MB of exception tables. I don't know how many of them are exceptions we recover from vs we terminate. So we might investigate adding the `nothrow` specifier on methods so the except table is not created (not sure how we'll do this in an elegant way only for mobile, nor how we use exceptions, just throwing this here as a thought)

-`__const` is also fairly big (~800K) quickly checking this I think protos are the biggest offenders here (you can also check this by the same `otool -l` / `dd` for that section)

I will try to do a deeper analysis but please don't block on me. Hope this gives you more ideas where to look.

**Comment by mattklein123** [comment]
Thanks @junr03 and @Reflejo. A couple of things from me:
1) We shouldn't bother with anything other than `-c opt --copt -Os`. `-c dbg` isn't optimized. @junr03 can we make sure we only look at that from now on?
2) Just to make sure we are speaking the same language at all times, can we report both uncompressed size after final linking and stripping, as well compressed size? That will give us a good place to start.
3) Then yeah we can start actually looking at figuring out where size is being spent.

@junr03 my advice is to actually just schedule 30-45 minutes with @Reflejo as I think the time will be well worth it. I can sit with you also for a bit once you do that, but I mainly want to make sure we have the right tooling and outputs in place to begin measurement. I don't think it's actually worth looking at where the space is being spent until we do that. Thank you!

**Comment by mattklein123** [comment]
(You should be able to get full symbols on top of the opt build via `--copt --gdb3` also). It's possibly that the tool you are using might have to be modified in some way to get the data that we need but it should all be there. This is where I think @Reflejo can help pretty quickly. Anyway, again, let's make sure we have the baseline methodology in place before we do anything else (strip logging, etc.). This is roughly:
1) Compile size optimized with symbols across all deps
2) Size of binary after linking/stripping
2) Compressed size of binary

**Comment by junr03** [comment]
Thanks for the comments @Reflejo and @mattklein123 

I do agree with you that the most representative way to look at the binary is by using the `test_binary` target I have described in the issue. My current trouble there is that I can only compile against x86. Further I do think that a good last signal in the process for any change we make should be seeing the delta in size between final app binary sizes (both in ios and android).

So I think the basic methodology we should use is (paraphrasing Matt's proposal and adding my own thoughts):
1. Compile `test_binary` against **arm64** size optimized with symbols
2. Strip the binary, measure size
3. Compress the binary, measure size
4. Compile demo app (ios and android), measure size.

Then make changes and repeat, measuring deltas.

Questions for you:
1.  Do you think this is an acceptable methodology? If it is I can establish all the tooling necessary to do so.
2. Related to `1` I do think it is important for us to be able to compile `test_binary` against arm64. This is the only part of our testing steps that is not done, but I can invest in that today.
3. Both you and Matt have not mentioned measuring deltas in the final app bloat, but isn't that a final representation of any change that we make. i.e we should see how we are moving the needle on this front with changes we embark on?

Let me know what you think. Once I have this down, and can iterate efficiently we can pair for a bit to follow up on your ideas (e.g the exception idea). I can schedule some time for monday @Reflejo.

**Comment by mattklein123** [comment]
> Do you think this is an acceptable methodology? If it is I can establish all the tooling necessary to do so.

In general yes, but we need to also include tooling to actually see where the size is being spent. I would not worry about making any changes right now. Once we start making changes, yes, we need to definitely measure the deltas and keep track of the current size in CI so we don't regress without knowing it.

> Related to 1 I do think it is important for us to be able to compile test_binary against arm64. This is the only part of our testing steps that is not done, but I can invest in that today.

Sure, this would be optimal, but I thought there was some issue here. I'm also not sure why we can't effectively just do this with the iOS/Android targets but I don't know the details. Can we time box getting this working and circle back? I do know that many people in the community are compiling Envoy for ARM, but I think they do this on an ARM host vs. cross-compile, but I'm not sure. cc @moderation. 

> Both you and Matt have not mentioned measuring deltas in the final app bloat, but isn't that a final representation of any change that we make. i.e we should see how we are moving the needle on this front with changes we embark on?

Yes, but let's not worry about changes right now. Let's get the methodology down on how to compile and measure what we have, and present a tabular view of where the size is being spent.

**Comment by junr03** [comment]
> need to also include tooling

Right now the tool that has given me most information is bloaty. However, part of the time I will setup with @Reflejo is to learn what his toolkit is for investigations like this. I will document so that it is repeatable in the future.

> Can we time box getting this working and circle back?

Yep, that is what I am doing right now. Won't extend further than this afternoon. I chatted with @moderation yesterday and they are compiling on native hosts. I chatted with @keith about cross compiling via bazel on x86 and he advised that was a rough path. The last path I am exploring today is Docker, which arguable supports multi-arch out of the box.

**Comment by mattklein123** [comment]
If it really comes down to it just buy a Raspberry Pi or similar to do the investigation on, but it seems like that shouldn't be needed.

**Comment by mattklein123** [comment]
Also, I don't know what bloaty is, but all of the data should be available via objdump and related tools, and can be scripted as needed.

**Comment by moderation** [comment]
Hopefully @junr03 investigation into cross compilation pays off but if not I'm using a Pine64 RockPro64 SOC - https://www.pine64.org/rockpro64/. 4G board is $80. You'll want the big heat sink. Has enough memory and cores to compile stuff like Bazel, Envoy, CockroachDB etc.

**Comment by costinm** [comment]
Not sure if it helps - the binary I built about 1 year ago - https://github.com/costinm/istio-build/releases - is 5M for android/arm (stripped). Maybe we can compare.

Looking at the arm build for android - it is a bit smaller (https://github.com/lyft/envoy-mobile/issues/153)

**Comment by kastiglione** [comment]
`envoy_cc_library()` declares `alwayslink = 1`:

https://github.com/envoyproxy/envoy/blob/ad57ed8511b636869afb3eef3c21b52890d71890/bazel/envoy_library.bzl#L64

I'm not sure how many of the libraries truly need to be force loaded, but this blocks the `-dead_strip` optimization of ld64 (iOS). Rerunning the link command with all `-force_load` flags removed, **except** `libenvoy_main_interface_lib`, reduced the `test_binary` size by 2mb (down to ~10mb from ~12mb, both using `-dead_strip`). So there's upper limit of 2mb reduction by using `alwayslink` only where needed.
