### ISSUE TITLE
android: Gradle builds fail depending on AAR manifest with missing package

### ISSUE THREAD

**Issue by costinm** [lyft/envoy-mobile#170]
This is against master (79dc7346047aa9c3b78d89af2d850ef75a97c0c1), built using

```
BUILD_IMAGE=envoyproxy/envoy-build:ec38ecb88fd1abe55ab1daa2f6bd239ffccc9d98

build:
	docker run -it --rm -v `pwd`:`pwd` -w `pwd` \
    -v ${ANDROID_HOME}:/Android -v ${ANDROID_NDK_HOME}:/AndroidNDK \
    -e ANDROID_HOME=/Android -e ANDROID_NDK_HOME=/AndroidNDK \
    --name envoy ${BUILD_IMAGE} bazel build android_dist --config=android
```

I get an error about manifest merging. Note that the released aar doesn't have this problem 
( but doesn't have arm jni lib, so have to build )

```
 Task :app-dmesh:processDebugManifest FAILED
[envoy.aar] /home/costin/.gradle/caches/transforms-2/files-2.1/2476fcf30cdbad53a0acb5a29bb94775/AndroidManifest.xml:2:1-6:12 Error:
	Missing 'package' declaration in manifest at [envoy.aar] AndroidManifest.xml:2:1-6:12
[envoy.aar] /home/costin/.gradle/caches/transforms-2/files-2.1/2476fcf30cdbad53a0acb5a29bb94775/AndroidManifest.xml Error:
	Validation failed, exiting
```

Looking at the manifest - the package was indeed empty in the built .aar.

Workaround: extract the jni file and copy to my project, add the java package as well as source (instead of using the aar).

Menu inside the built aar looks like:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="">
   <application>
   </application>
</manifest>
```

**Comment by junr03** [comment]
@buildbreaker do you have time to try and repro this locally? I have not seen this before.

**Comment by keith** [comment]
When we were working on this we knew the manifest had this content, but didn't see it causing any issues. Hopefully @buildbreaker can repro and we can fix

**Comment by costinm** [comment]
I used standard Android Studio, with the .aar added in the gradle file.

**Comment by goaway** [comment]
@costinm Thanks for reporting this, we will try to repro and follow up.

**Comment by buildbreaker** [comment]
@costinm Thanks for reporting. What a bummer that you're running into issues with building! 

With the docker image you provided, I do get another error when building:
```
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/tmp/tmp.pYTyGfSFut/CMakeFiles/CMakeOutput.log".
```

I want to make sure I am able to emulate your steps to reproduce (and also use it as a way to verify a fix). Could you provide a bit more information:
1. Are there other commands you may have missed in the description for initiating a problematic aar build?
1. What bazel build flags are you adding to get your arm jni lib?
1. What is the gradle project set up you have?

I'd like to take a closer look with the details you provide. I do remember seeing that odd manifest being generated somewhere with @keith at one point but it ended up not being an issue when we were testing things out

**Comment by costinm** [comment]
Sorry for the delay. My build:
```
$ cat Makefile

# Builder image for local run.
# TODO: add android SDK and NDK to the image (so they are cached and reproductible). Needed for running in CI
BUILD_IMAGE=envoyproxy/envoy-build:ec38ecb88fd1abe55ab1daa2f6bd239ffccc9d98

# Optional local file to set ANDROID_HOME and ANDROID_NDK_HOME
-include env.mk

pull:
	git pull --recurse-submodules

build:
	docker run -it --rm -v `pwd`:`pwd` -w `pwd` \
    -v ${ANDROID_HOME}:/Android -v ${ANDROID_NDK_HOME}:/AndroidNDK \
    -e ANDROID_HOME=/Android -e ANDROID_NDK_HOME=/AndroidNDK \
    --name envoy ${BUILD_IMAGE} bazel build android_dist --config=android
$ make pull build
... 
Target //:android_dist up-to-date:
  bazel-bin/android_out
INFO: Elapsed time: 394.045s, Critical Path: 84.01s
INFO: 2784 processes: 2770 local, 14 worker.
INFO: Build completed successfully, 3691 total actions

```

**Comment by costinm** [comment]
And it looks like it is fixed:

```
$ ls -l  dist/envoy.aar 
-rwxr-xr-x 1 root root 30354150 Jul  8 14:32 dist/envoy.aar

$ unzip -x dist/envoy.aar AndroidManifest.xml
Archive:  dist/envoy.aar
  inflating: AndroidManifest.xml   

$ cat AndroidManifest.xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="library.kotlin.io.envoyproxy.envoymobile" >

    <application>
    </application>

</manifest>
```

**Comment by buildbreaker** [comment]
Thanks for circling back and verifying @costinm :)
