### ISSUE TITLE
testing: develop test plan and agree on contribution guidelines

### ISSUE THREAD

**Issue by buildbreaker** [lyft/envoy-mobile#197]
We want to have a testing strategy and guidelines for envoy mobile:
1. Unit test coverage
1. End to end testing strategy for the library
1. UI testing strategy

Open questions:
1. What should our test coverage percentage be?
1. How exhaustive do we want to be for end to end testing?
1. What UI tests do we think are valuable to have
1. How can we enforce these guidelines in CI?

We can take ideas from [envoy](https://github.com/envoyproxy/envoy) and [cronet](https://chromium.googlesource.com/chromium/src/+/master/components/cronet/)

The primary goal here is for us to talk about where we want to get to.

cc: @rebello95 @goaway @junr03 @cafedomingo

**Comment by rebello95** [comment]
A couple things I'd like to add:

- Ideally we can enforce the same % of code coverage used in upstream Envoy
- It'd be nice to a) fail CI if code coverage drops below this percentage, and b) warn authors if code coverage decreases at all

**Comment by rebello95** [comment]
Linking this issue in the docs being added for testing in https://github.com/lyft/envoy-mobile/pull/538

**Comment by rebello95** [comment]
As part of this issue, we should also make sure to add a test coverage CI job

**Comment by rebello95** [comment]
As part of this issue, we should make sure we have testing covered for the bridging layer between C/Java/ObjC to help prevent issues like https://github.com/lyft/envoy-mobile/pull/703

**Comment by junr03** [comment]
We also need to add tests for the engine class #707

**Comment by junr03** [comment]
I am moving this issue to the backlog as it is a long standing issue that links all of our ideas. The individual issues to tackle each of the ideas mentioned here can be in their own milestones.

**Comment by rebello95** [comment]
Note: Due to the amount of time upstream Envoy takes to run test coverage (~4 hours), coverage is likely something that we'll want to run as a cron on master of Envoy Mobile to avoid bloating PR CI times.

**Comment by junr03** [comment]
I broke up all the ideas in here to their own issues and tagged them under https://github.com/lyft/envoy-mobile/labels/area%2Ftesting. If you have an idea related to testing please open up an individual issue.
