### ISSUE TITLE
ci: bazel run does not start the simulator

### ISSUE THREAD

**Issue by junr03** [lyft/envoy-mobile#201]
When trying to run the iOS apps with `bazel run` in CI, the CI job fails with `Failed to launch the simulator. The existing simulators are`. It is unclear why `bazel run` does not start the simulator in CI but does locally. 

In order to circumvent this problem, CI currently manually starts the simulator using `ios-sim`

**Comment by keith** [comment]
`bazel run` should definitely launch the simulator. I can look into this at some point

**Comment by rebello95** [comment]
Closing as we don't use `ios-sim` anymore.
