### ISSUE TITLE
performance: use kqueue with libevent on Apple platforms

### ISSUE THREAD

**Issue by rebello95** [lyft/envoy-mobile#215]
### Context

Based on [this discussion](https://github.com/lyft/envoy-mobile/issues/113#issuecomment-507421778), we are seeing that `libevent` is using polling on iOS instead of `kqueue`.

This is extremely unperformant, and is causing Envoy Mobile to use ~100% CPU on iOS devices.

To validate that this was the root cause, we were able to hardcode an entry in [this file](https://github.com/envoyproxy/envoy/blob/master/bazel/foreign_cc/BUILD#L96) to force `kqueue` to be enabled:

`"EVENT__HAVE_WORKING_KQUEUE": "on"`

After building, we could verify that the expected conditional was defined:

```
mrebello-mbp151:envoy-mobile mrebello$ cat ./bazel-out/ios-x86_64-min10.0-applebin_ios-ios_x86_64-fastbuild/bin/external/envoy/bazel/foreign_cc/event/include/event2/event-config.h|grep WORKING
#define EVENT__HAVE_WORKING_KQUEUE 1
```

**When running Envoy on a device, CPU went from ~100% to just 1.5% with this change.**

### Task

Apply an upstream fix that enables `kqueue` on Apple/iOS platforms so that we can fix this performance issue on iOS.

**Comment by keith** [comment]
Here's a upstream libevent fix so we don't have have to explicitly set this only for Apple targets https://github.com/libevent/libevent/pull/849

**Comment by rebello95** [comment]
Updating envoy upstream with the libevent fix: https://github.com/envoyproxy/envoy/pull/7453
