### ISSUE TITLE
objc: fix lib rule to include necessary header

### ISSUE THREAD

**Issue by junr03** [lyft/envoy-mobile#230]
#188 migrated the library layer to swift. It needed a lot of complex bazel work to support the design we had adopted. In the way we broke the objective-c demo, as a necessary header is not included in the static framework.

@goaway understands the problem and will fix as expediently as possible.

**Comment by kastiglione** [comment]
I've opened a couple related issues. https://github.com/bazelbuild/rules_swift/issues/291 https://github.com/bazelbuild/rules_apple/issues/557. Neither of these are blocking, but they'd be helpful. cc @rebello95

**Comment by rebello95** [comment]
Thanks so much for your help with this @kastiglione.

https://github.com/bazelbuild/rules_apple/issues/557
