### ISSUE TITLE
swift: add LogLevel to startup interfaces

### ISSUE THREAD

**Issue by rebello95** [lyft/envoy-mobile#244]
A `LogLevel` enum was added to the Kotlin interfaces in https://github.com/lyft/envoy-mobile/pull/194, but is not yet available on iOS/Swift. We should implement something similar for iOS.

**Comment by rebello95** [comment]
This is actually available in the Objective-C layer, but we should move it to Swift: https://github.com/lyft/envoy-mobile/blob/2f3b0be690b8bcae1809f4e3f56f7101cbc0e416/library/objective-c/Envoy.h

**Comment by rebello95** [comment]
https://github.com/lyft/envoy-mobile/pull/245

**Comment by buildbreaker** [comment]
Yeah, let's get the consistency between Kotlin and Swift here
