### ISSUE TITLE
Android demo doesn't pack multiple architectures from Envoy mobile aar

### ISSUE THREAD

**Issue by buildbreaker** [lyft/envoy-mobile#28]
Building the Android demo can only be built with a single architecture.

The current `android_binary` Bazel rule has a bug (https://github.com/bazelbuild/bazel/issues/8283) where it doesn't pack multiple architectures from `aar_imports`. Underneath the `android_binary`, it uses `aar_imports` for any `aar` dependencies.

Any Android applications using Bazel depending on Envoy Mobile will have this issue.

**Comment by junr03** [comment]
@buildbreaker we fixed this with the fat apk, didn't we? If that is the case do you mind commenting and closing?

**Comment by buildbreaker** [comment]
@junr03 Correct. This is not really that important since we are able to build a fat aar.
