### ISSUE TITLE
core: create post-init callback

### ISSUE THREAD

**Issue by goaway** [lyft/envoy-mobile#285]
This allows some setup to happen automatically, and would allow us to queue and then drain requests submitted during startup, rather than failing them.

The hack to work around this is to `sleep` longer than it takes Envoy to start up and then call `setup`, which is pretty unfortunate.

**Comment by buildbreaker** [comment]
Ran into this issue when trying to integrate Envoy into the Lyft Android app. I'm planning to do a blocking thread sleep of 2 seconds as a development work around here (to unblock the current task of the integrating Envoy)

This is a very interesting problem :)
