### ISSUE TITLE
platform: unify EnvoyError type between platforms

### ISSUE THREAD

**Issue by junr03** [lyft/envoy-mobile#409]
Currently the `EnvoyError` type is defined in Java and in Swift. I believe the Swift type should be pushed down to objective-c. Unfortunately we have struggled with using objective-c types in Swift before (for example: https://github.com/lyft/envoy-mobile/pull/407).

**Comment by rebello95** [comment]
If we're not able to push the type down to Objective-C because of Swift segfaults, what about moving Java's up to Kotlin?

**Comment by rebello95** [comment]
Discussed with @junr03 offline, and we should update the Android `EnvoyError` to be Kotlin so as to only expose Kotlin/Swift types publicly to consumers.

**Comment by rebello95** [comment]
https://github.com/lyft/envoy-mobile/pull/539
