### ISSUE TITLE
config: support dynamic_forward_proxy

### ISSUE THREAD

**Issue by rebello95** [lyft/envoy-mobile#433]
We currently have a `dynamic_forward_proxy` configuration in the base config file that's checked in to the repo, but it doesn't function when using the direct API (and the `base` cluster must be used with a hardcoded domain for now).

We'll need to support the `dynamic_forward_proxy` configuration so consumers don't need to pre-define acceptable domains for routing when creating Envoy instances.

**Comment by junr03** [comment]
fixed by #616
