### ISSUE TITLE
size: investigate binary increase in envoy

### ISSUE THREAD

**Issue by junr03** [lyft/envoy-mobile#447]
After #388 the binary size increased. We need to investigate what parts of the binary increased.

**Comment by junr03** [comment]
another commit that increased the binary size: https://github.com/lyft/envoy-mobile/pull/554

**Comment by junr03** [comment]
and one more: https://github.com/lyft/envoy-mobile/pull/607

We will prioritize another pass in size analysis early January.

**Comment by junr03** [comment]
and the one that broke the camel's back: #626

**Comment by junr03** [comment]
I want to make sure that I run the analysis over everything that we will need for v0.3. Hence it will also include this: https://github.com/lyft/envoy-mobile/pull/645

**Comment by rebello95** [comment]
Seeing another increase in https://github.com/lyft/envoy-mobile/pull/663

**Comment by rebello95** [comment]
Closing this issue in favor of other issues tagged with `perf/size` and https://github.com/lyft/envoy-mobile/issues/710

**Comment by junr03** [comment]
keeping this issue closed, but noting this https://github.com/lyft/envoy-mobile/pull/923 pr as a point that should be analyzed as the bump is pretty significant.
