### ISSUE TITLE
android: gRPC codec with e2e testing

### ISSUE THREAD

**Issue by buildbreaker** [lyft/envoy-mobile#489]
Mirror: https://github.com/lyft/envoy-mobile/pull/416

Create e2e testing using a gRPC generated server:

1. Integrate protobuf bazel rules with our tests + add simple echo service: ttps://github.com/lyft/envoy-mobile/pull/473
1. Build java library with JNI: hhttps://github.com/lyft/envoy-mobile/pull/474
1. Implement gRPC codec with end to end testing for higher confidence: https://github.com/lyft/envoy-mobile/pull/472

**Comment by junr03** [comment]
done in https://github.com/lyft/envoy-mobile/pull/472
