### ISSUE TITLE
docs: create documentation file for releasing process

### ISSUE THREAD

**Issue by rebello95** [lyft/envoy-mobile#579]
We should add a documentation file outlining the process for cutting new releases of Envoy Mobile.

Current steps required from a high level:

- Update `.podspec` file version
- Update `VERSION` file
- Update releases `rst` file
- Perform the [CocoaPods incantations](https://github.com/lyft/envoy-mobile/issues/578)
- Publish release including the iOS, Android, and CocoaPods artifacts
- Publish podspec update to specs repo

**Comment by junr03** [comment]
closed by https://github.com/lyft/envoy-mobile/pull/625
