### ISSUE TITLE
callbacks: only ever surface one final callback

### ISSUE THREAD

**Issue by goaway** [lyft/envoy-mobile#592]
From Slack:

For practicality, we’re going to abandon our previous convention of always dispatching cancelation callbacks regardless of whether you had received a complete server response or error. previously we did this because in theory the request could still have been in flight, and thus it would still be valid in some sense to cancel it.

But this makes it harder to map to common types of handler patterns, and we were running into cases where we were introducing client synchronized state to try to work around this, which seems detrimental.

So the new contract (we’re proposing) will be this:
In response callbacks you will only ever receive one of:
1) a final response state (headers, data or trailers)
2) an error
3) a cancellation

**Comment by junr03** [comment]
This was fixed by #616.
