### ISSUE TITLE
core: support (gzip) compression/decompression

### ISSUE THREAD

**Issue by rebello95** [lyft/envoy-mobile#664]
### Overview

We'd like to add support for compressing/decompressing requests/responses (i.e., using gzip or brotli) from within an L7 C++ filter in Envoy Mobile.

### Context

Envoy currently supports a [gzip filter](https://www.envoyproxy.io/docs/envoy/v1.13.0/configuration/http/http_filters/gzip_filter#config-http-filters-gzip) and corresponding [configuration](https://www.envoyproxy.io/docs/envoy/v1.13.0/api-v3/extensions/filters/http/gzip/v3/gzip.proto). **This filter supports compressing responses from a service based on the size of the response body and other pre-set configurations. However, it does not support decompressing requests.**

### Goal

Ideally, there are 4 variants of compression/decompression that would be supported in order to transparently support an end-to-end compression solution within Envoy/Envoy Mobile:

|  | Action | Entity | Supported by Envoy? |
|---|:----------------:|:-----------------:|:--------------------:|
| 1 | Compression | Outbound response | **YES** |
| 2 | Decompression | Inbound request | NO |
| 3 | Compression | Outbound request | NO |
| 4 | Decompression | Inbound request | NO |

Implementing this functionality in filter(s) would allow Envoy and Envoy Mobile to make decisions on which requests/responses need to be compressed, and to decompress as necessary.

### Changes

An issue was opened in upstream Envoy (https://github.com/envoyproxy/envoy/issues/4445) requesting that decompression of inbound requests be supported. Some work is being done on this already in https://github.com/envoyproxy/envoy/pull/7057 (refactoring the existing gzip filter to more generically act as a "compression" filter), and @rojkov has a [branch](https://github.com/rojkov/envoy/tree/decompress) that goes further down this path.

The [Generic Compression Filter proposal document](https://docs.google.com/document/d/16U0i_X4iO8kqjUtrqMd-LgNEFzwAXzqn4JBH-cOx3Aw/edit) linked in the above discussion also outlines the 4 aforementioned compression options as goals.

I made an [upstream change](https://github.com/envoyproxy/envoy/pull/9942) to allow us to force-link the existing gzip filter from Envoy Mobile and was able to test [integrating the filter into Envoy Mobile's filter chain](https://github.com/lyft/envoy-mobile/commit/28b1e1f646b6dbf1df034f9eb925069cb0834451). We intend to utilize the compression functionality written into Envoy as it becomes available.

**Comment by Augustyniak** [comment]
Will it be possible for `EnvoyMobile` callers (users of `EnvoyMobile` library) to get access to L4 requests' sizes if we starts gzipping outbound requests using L7 Envoy filter (as mentioned in the write-up above)? Access to L4 sizes would allow us to log them using our analytics pipeline so that we could perform offline analysis on this data.

**Comment by rebello95** [comment]
That's a good call out, @Augustyniak. Definitely something we should look into and keep top of mind when implementing this feature 👍

**Comment by yorudy** [comment]
Is this still on track for March 18 2020 delivery? I have a use case that depends on envoy supporting gzip compression for incoming requests.

**Comment by rebello95** [comment]
Yes, this is actively being worked on. @junr03 is wrapping up changes in https://github.com/envoyproxy/envoy/pull/11172, after which we should be able to update Envoy Mobile with the required configs.

**Comment by yorudy** [comment]
Thanks for the update @rebello95. Looks like the pr was minted yesterday. This is exciting! 

I'm eager to see this land in mainline so [Gloo ](https://gloo.solo.io/) can expose config for it. Would be sweet if [enabling gzip in Envoy for Gloo](https://docs.solo.io/gloo/latest/installation/advanced_configuration/gzip/) just goes bi-directional (Response AND Request) by default!

**Comment by rebello95** [comment]
Resolved by https://github.com/lyft/envoy-mobile/pull/861 (thank you @junr03 and @rojkov!)

**Comment by Charana123** [comment]
@rebello95 Is compression of the outbound request (your 3rd variant) supported yet ? The [compression filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/compressor_filter#config-http-filters-compressor) says otherwise.
