### ISSUE TITLE
dns: stuck if started without connectivity

### ISSUE THREAD

**Issue by junr03** [lyft/envoy-mobile#672]
Creating this to track merging and releasing https://github.com/envoyproxy/envoy/pull/9899.

This problem was first observed in Envoy Proxy, but was first reliably reproduced in Envoy Mobile iOS. Further explanation is written down in https://github.com/envoyproxy/envoy/issues/4543#issuecomment-580915046

**Comment by rebello95** [comment]
Fix is going in with https://github.com/lyft/envoy-mobile/pull/663, but more investigation will be done in https://github.com/lyft/envoy-mobile/issues/673.
