### ISSUE TITLE
core: sigabort in histogram code 

### ISSUE THREAD

**Issue by junr03** [lyft/envoy-mobile#688]
```
SIGABRT: 

0  libsystem_kernel.dylib  ___pthread_kill
1  libsystem_pthread.dylib _pthread_kill$VARIANT$armv81
2  libsystem_c.dylib       _abort
3  Lyft                    Envoy::Stats::HistogramStatisticsImpl::refresh(histogram const*) (Lyft)
4  Lyft                    Envoy::Stats::ParentHistogramImpl::merge() (Lyft)
5  Lyft                    Envoy::Stats::ThreadLocalStoreImpl::mergeInternal(std::__1::function<void ()>) (Lyft)
6  Lyft                    std::__1::__function::__func<Envoy::Stats::ThreadLocalStoreImpl::mergeHistograms(std::__1::function<void ()>)::$_2, std::__1::allocator<Envoy::Stats::ThreadLocalStoreImpl::mergeHistograms(std::__1::function<void ()>)::$_2>, void ()>::operator()() (Lyft)
7  Lyft                    Envoy::Event::DispatcherImpl::runPostCallbacks() (Lyft)
8  Lyft                    event_process_active_single_queue (Lyft)
9  Lyft                    event_base_loop (Lyft)
10 Lyft                    Envoy::Server::InstanceImpl::run() (Lyft)
11 Lyft                    Envoy::MainCommonBase::run() (Lyft)
12 Lyft                    Envoy::Engine::run(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) (Lyft)
13 Lyft                    void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, envoy_status_t (Envoy::Engine::*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >), Envoy::Engine*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >(void*) (Lyft)
14 libsystem_pthread.dylib __pthread_start
```

**Comment by junr03** [comment]
note that this issue is extremely low frequency (~5 times in the last 6 weeks with thousands of sessions in hundreds of clients at Lyft) and happened before the major refactor in #616

**Comment by junr03** [comment]
@jmarantz, sorry to pull you in here. I came back to this today, and re-read the histogram code. I am a little bit at a loss about how we could be triggering either of the assertions in the refresh code. All manipulations of the two vectors should ensure that we end up with the supported number of elements...

Do you have any intuition about what might be happening here?

**Comment by junr03** [comment]
@ramaraochavali in https://github.com/envoyproxy/envoy/issues/10179 you mentioned the previous merge messing up with data. Well, what is interesting is that we noticed that another crash started happening after we started flushing metrics by manual triggers #748. That problem is more simple, as it makes sense that we are hitting the assertion.

However, what is interesting is that the crash reported in _this issue_ saw an uptick in occurrences since we started doing manual flushes (vs. in the past is happened _very very rarely_). So I am wondering if it is possible that a previous merge is messing up a current merge. However, what gives me less confidence in that theory is that the assert triggered in #748 should protect us against my theory.

Obviously, there is also the possibility that the uptick in this crash since the introduction of #748 might just be a red herring, correlation != causation and all, but it seems suspicious. 

lmk if you have any further thoughts.

**Comment by ramaraochavali** [comment]
Just to clarify on my previous comment about the previous merge messing with the current merge, I did not mean they are running in parallel - If they were running in parallel, the merge_in_progress assert will protect us.

What I meant was at https://github.com/envoyproxy/envoy/blob/master/source/common/stats/histogram_impl.cc#L67 we call `hist_approx_quantile` to compute the quantiles for the new histogram. That populates the `computes_quantiles_` vector. If that call for example populates incorrectly, we would come to know about that only in the next merge because assert at line 66 would fire when it is firing next time.  We should probably assert immediately after the call to `hist_approx_quantile` - otherwise `computed_quantiles_` is never altered outside of this call. This theory is assuming that you are hitting that assert some how. Does this make sense?

 I do not know enough prometheus part to confirm about computed buckets though. 

Any way, let us see what you find.

**Comment by ramaraochavali** [comment]
@junr03 Just curious, did you find any thing on this?

**Comment by junr03** [comment]
Hi @ramaraochavali so sorry for not updating this, I totally missed your last two messages. Your clarification makes total sense, I agree that that is how subsequent calls could mess up the assertion. Of course the calls could not run in parallel, as protected by the assertion.

I don't have anything to report as of yet. After #749, the rate of this crash went back down to _very_ sporadically, so I de-prioritized it for the time being. I will update this once I pick it back up.

**Comment by ramaraochavali** [comment]
@junr03 No problem. Thanks for the details and will wait to see what you find.

**Comment by junr03** [comment]
In trying to repro #838 reliably, I actually found a 100% repro for this crash! It helped me understand what is _actually_ happening here. `HistogramStatisticsImpl` has a `static const std::vector<doubles>` [here](https://github.com/envoyproxy/envoy/blob/49efb9841a58ebdc43a666f55c445911c8e4181c/source/common/stats/histogram_impl.cc#L29) and [here](). On the other hand, Envoy Mobile's Engine has a static lifecycle held by a shared_ptr [here](https://github.com/lyft/envoy-mobile/blob/b52e4f95356e1f5061888bc61218d2b1e567624c/library/common/main_interface.cc#L80). The thread that runs the envoy event loop exits via `~Engine()`. Thus, because there static destruction outside of compilation units is undefined, it is possible for the static vector in the histogram class to be destroyed while the envoy event loop is still running. And thus, during a histogram merge, the assert comparing the supported vs the computed quantiles would fail.

The fix here is to pursue [instance-based](https://github.com/lyft/envoy-mobile/issues/332) engines that do not have a static lifetime.

cc @ramaraochavali in case you are curious

**Comment by ramaraochavali** [comment]
@junr03 Great find and thank you for the update.

**Comment by jmarantz** [comment]
Should we just make the static vector of doubles be a c array, or lazy init
it per style guide?

There are also a daily significant number of static std:: string and other
small structures in the code base. Maybe we should add a help-wanted bug to
eliminate all of those? Maybe with a format-check to ensure no more are
added?

**Comment by ramaraochavali** [comment]
lazy init sounds good to me - Envoy PR https://github.com/envoyproxy/envoy/pull/11127

**Comment by junr03** [comment]
> Should we just make the static vector of doubles be a c array, or lazy init it per style guide?

Yep, way easier than solving on our side. Thanks :)

**Comment by junr03** [comment]
> Maybe we should add a help-wanted bug to eliminate all of those? Maybe with a format-check to ensure no more are added?

https://github.com/envoyproxy/envoy/issues/11130
