### ISSUE TITLE
Njie’s File 

### ISSUE THREAD

**Issue by Njierahim** [lyft/envoy-mobile#725]
var a =("Good first issues”)! 
Function(docs: [add section for envoy client builder options])!
Function.(docs: [add flowchart diagram for stream lifecycle])!;
console.log(a);
function(b)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    console.log (ubuntu-latest);

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

**Comment by junr03** [comment]
Hi @Njierahim, thanks for posting this.

Could you expand a bit on what you are trying to do? I am not sure I understand from this issue

**Comment by Njierahim** [comment]
Yes
Thank you!!

On Mar 5, 2020, at 3:00 AM, Jose Ulises Nino Rivera <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @Njierahim<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNjierahim&data=02%7C01%7CNjie02%40email.franklin.edu%7C0474a0d317994546da1308d7c0e3a858%7C5f846636437d46ba9152d0632a997016%7C1%7C0%7C637189956325862220&sdata=f0QgxzhYQj7nk3eDIkM8nPCEhvDanChq%2Bubw2regHLs%3D&reserved=0>, thanks for posting this.

Could you expand a bit on what you are trying to do? I am not sure I understand from this issue

**Comment by Njierahim** [comment]
Hi Good Morning,

Under Description of the feature request
I develop a test code for the Istio DNS<https://preliminary.istio.io/docs/tasks/security/dns-cert/> task in order to provide automated testing of the Istio.io<http://Istio.io> website for my releases. In JavaScript development



On Mar 5, 2020, at 3:00 AM, Jose Ulises Nino Rivera <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @Njierahim<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNjierahim&data=02%7C01%7CNjie02%40email.franklin.edu%7C0474a0d317994546da1308d7c0e3a858%7C5f846636437d46ba9152d0632a997016%7C1%7C0%7C637189956325862220&sdata=f0QgxzhYQj7nk3eDIkM8nPCEhvDanChq%2Bubw2regHLs%3D&reserved=0>, thanks for posting this.

Could you expand a bit on what you are trying to do? I am not sure I understand from this issue

**Comment by junr03** [comment]
Sorry, it’s still unclear to me what you’re trying to accomplish. If you want to provisión a new certificate to use with your deployment that would be done in your own infrastructure. 

Also, did you mean to open up an issue against github.com/envoyproxy/envoy? Or istio itself? I’m not sure how this relates to envoy-mobile

**Comment by Njierahim** [comment]
Sorry. But i still can't understand you

Database Administration(CITP-DBA)
Data Modeling Cyber Security (CITP-CYBR)
Columbus, Ohio
Tel: 614-643-0014 ex 2018
Fax: 614-227-0155

On Mar 5, 2020, at 6:59 AM, Jose Ulises Nino Rivera <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry, it’s still unclear to me what you’re trying to accomplish. If you want to provisión a new certificate to use with your deployment that would be done in your own infrastructure.

Also, did you mean to open up an issue against github.com/envoyproxy/envoy?<http://github.com/envoyproxy/envoy?> Or istio itself? I’m not sure how this relates to envoy-mobile

**Comment by junr03** [comment]
Based on the information provided this is not an issue with Envoy Mobile. I think you probably want to open an issue against Istio or Envoy.

Lmk if I am mistaken
