### ISSUE TITLE
ci: update Azure to allow external access

### ISSUE THREAD

**Issue by rebello95** [lyft/envoy-mobile#74]
Right now the Azure organization used for CI doesn't allow contributors to this repo to see details on CI jobs. We'll need to update these policies to allow others to see this information.

@junr03 feel free to add more details here.

**Comment by junr03** [comment]
This is done. I have created an envoy-mobile org that has a public project for this repo. All contributors should be able to see jobs. All maintainers have access to re-kick jobs.
