### ISSUE TITLE
grpc: remove grpc status from onHeaders closure

### ISSUE THREAD

**Issue by junr03** [lyft/envoy-mobile#746]
I noticed that our gRPC clients inspect headers for `grpc-status`. However, according to protocol `grpc-status` is sent on trailers.

Our Response handler code should be fixed to not have status as an argument in the on headers closure, as right now we will always send `0` indicating success even when that is not the case.

Swift: https://github.com/lyft/envoy-mobile/blob/master/library/swift/src/GRPCResponseHandler.swift#L41
Kotlin: https://github.com/lyft/envoy-mobile/blob/master/library/kotlin/src/io/envoyproxy/envoymobile/GRPCResponseHandler.kt#L39

**Comment by rebello95** [comment]
This was done in my recent refactoring of the Swift/Kotlin interfaces https://github.com/lyft/envoy-mobile/pull/858 / https://github.com/lyft/envoy-mobile/pull/913
