### ISSUE TITLE
support c++17

### ISSUE THREAD

**Issue by junr03** [lyft/envoy-mobile#873]
The main issue on the envoy mobile side will be c++17 support on both iOS and Android. I did some light research a few months ago, and it seemed that modern versions of both should support it. However, there is no central place (that I could find) that show both language and library support in a matrix with the platforms. So doing some more rigorous research on that would be great.

There was some initial discussion on enabling on iOS, with initial abseil compatibility issues that arose at runtime [here](https://github.com/envoyproxy/envoy/pull/9654#issuecomment-587592397). 

My approach would be to work through issues as they come up trying to [build](https://envoy-mobile.github.io/docs/envoy-mobile/latest/start/building/building.html) and run the demo app on both [platforms](https://envoy-mobile.github.io/docs/envoy-mobile/latest/start/examples/hello_world.html) (iOS, Android) on all four platform languages (swift/objective-c, kotlin, java).

**Comment by rebello95** [comment]
Is there anything left with this now that https://github.com/lyft/envoy-mobile/issues/873 has landed?

**Comment by rebello95** [comment]
Is there anything remaining on this now that https://github.com/lyft/envoy-mobile/pull/964 has merged?
