### ISSUE TITLE
Convert Envoy's JNI library to Kotlin

### ISSUE THREAD

**Issue by buildbreaker** [lyft/envoy-mobile#99]

**Comment by buildbreaker** [comment]
A lot of interesting learnings here:
1. kotlin bazel rules don't quite handle transitive dependencies on `cc_library` like they do with java bazel rules
2. `android_binary` generation of aar's don't include transitive dependencies. This poses to be a problem because kotlin rules underneath create an extra layer of libraries which forces declared dependencies to be transitive

The fix here:
1. Create a `java_library` rule with an empty class to circumvent the issue with kotlin rules. Have the kotlin rule depend on this java library
2. Manually construct an aar using the kotlin library resulting jar rather than relying on the `android_binary` to do it

**Comment by buildbreaker** [comment]
Just to repeat the most critical information in the PR: this allows us to build Envoy mobile shim in kotlin rather than in strictly java.

**Comment by costinm** [comment]
That would force all apps using envoy library to also include the kotlin runtime.  Most apps are still written in plain java - a library forcing kotlin is not best practice, and I don't think the code used by envoy to wrap the native would benefit much from kotlin.

**Comment by buildbreaker** [comment]
We ended up splitting the Android component into two parts: the java JNI layer and the Kotlin layer which will expose a Kotlin api for applications to use.

The intent here is that we want to move forward with developing a Kotlin envoy mobile library but want to ensure that there is a path for folks who want a pure Java library in the future.

Going to close this for now since we aren't going to convert the JNI library completely to Kotlin.
