### ISSUE TITLE
error: unknown type name 'STACK_UNINITIALIZED'

### ISSUE THREAD

**Issue by Poorunga** [lyft/envoy-mobile#993]
when I run:
`# bazel build android_dist --config=android --fat_apk_cpu=x86,armeabi-v7a,arm64-v8a`

some error happend:
external/com_googlesource_googleurl/url/url_util.cc:187:3: error: unknown type name 'STACK_UNINITIALIZED'

**Comment by rebello95** [comment]
Hey @Poorunga 👋 we actually [debugged this issue over Slack a couple weeks ago](https://envoyproxy.slack.com/archives/CKQ2LK23G/p1594940114044900?thread_ts=1594904358.041500&cid=CKQ2LK23G) as well, so there's probably some helpful context in that thread. Can you try the following?

2 things I changed and was able to get it to work:
- Update ANDROID_NDK_HOME from `20**` to `21**` (i.e., `ANDROID_NDK_HOME=/Users/achiu/Library/Android/sdk/ndk/21.0.6113669`)
- Set `JAVA_HOME` to something like `/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home`
- Ensure both of these are in your `PATH`

Let me know if this fixes it for you!

**Comment by rebello95** [comment]
One other note: I also had to do a `bazelisk clean` after the above updates to get this to work locally

**Comment by Poorunga** [comment]
Thanks for answering my question. 

You seem to compile it on mac but I compile it on ubuntu.

According to your suggestion, 3 things I changed:
- Update `ndk version` from `19**` to `21**` (21.0.6352462)
- Update `jdk version` from `jdk1.8.0_202` to `jdk1.8.0_261`
- bazel clean

After these changes, the compilation passed, but the link fails, as shown in the following:
```
ERROR: /root/envoy-mobile/library/common/jni/BUILD:8:10: Linking of rule '//library/common/jni:libenvoy_jni.so' failed (Exit 1): clang failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/27749100e9bfff98a3d09e4f4ab4f7e1/execroot/envoy_mobile && \
  exec env - \
    BAZEL_LINKLIBS=-l%:libstdc++.a \
    BAZEL_LINKOPTS=-lm \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/root/jdk1.8.0_261/bin:/root/android-ndk-r21b:/root/sdk/tools:/root/sdk/platform-tools:/usr/local/go/bin:/data/gopath/bin \
    PWD=/proc/self/cwd \

......
```

**Comment by Poorunga** [comment]
Hi, @rebello95 , I changed the build command from:

`bazel build android_dist --config=android --fat_apk_cpu=arm64-v8a`

to:

`bazel build android_dist --config=android --fat_apk_cpu=armeabi-v7a`

Then the compilation was successful!

So, why does the link fail and the compilation fails when the architecture is `arm64-v8a`?

**Comment by rebello95** [comment]
Interesting, I'm glad you got it working @Poorunga. Not really sure why the other architecture in particular failed for you - are there any other logs from that failure? // @goaway or @keith if you have thoughts as well

**Comment by keith** [comment]
I think we're missing the full error from that, can you post some more of the output?

**Comment by Poorunga** [comment]
Thanks for answering my question. @keith @rebello95 

error output:
```
ERROR: /root/envoy-mobile/library/common/jni/BUILD:8:10: Linking of rule '//library/common/jni:libenvoy_jni.so' failed (Exit 1): clang failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/27749100e9bfff98a3d09e4f4ab4f7e1/execroot/envoy_mobile && \
  exec env - \
    BAZEL_LINKLIBS=-l%:libstdc++.a \
    BAZEL_LINKOPTS=-lm \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/root/jdk1.8.0_261/bin:/root/android-ndk-r21b:/root/sdk/tools:/root/sdk/platform-tools:/usr/local/go/bin:/data/gopath/bin \
    PWD=/proc/self/cwd \
  external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -shared -o bazel-out/android-arm64-v8a-fastbuild/bin/library/common/jni/libenvoy_jni.so ......
......
......
......
Execution platform: @local_config_platform//:host
bazel-out/android-arm64-v8a-fastbuild/bin/external/envoy/source/common/config/libutility_lib.lo: member bazel-out/android-arm64-v8a-fastbuild/bin/external/envoy/source/common/config/libutility_lib.lo(utility.pic.o) in archive is not an object
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //:android_dist failed to build
INFO: Elapsed time: 3015.792s, Critical Path: 104.84s
INFO: 2338 processes: 2338 local.
FAILED: Build did NOT complete successfully
```

**Comment by keith** [comment]
so this is the real error:

```
bazel-out/android-arm64-v8a-fastbuild/bin/external/envoy/source/common/config/libutility_lib.lo: member bazel-out/android-arm64-v8a-fastbuild/bin/external/envoy/source/common/config/libutility_lib.lo(utility.pic.o) in archive is not an object
```

🤔

**Comment by Poorunga** [comment]
So how do I solve this problem, or do you provide a `dockerfile` to make it simple?

**Comment by Poorunga** [comment]
I fixed the problem. 2 things I changed:

- Update clang from `clang-6` to `clang-9`
- Update g++ from `g++ 7.5` to `g++ 9`

Now, I have a `envoy.aar` based on `arm64-v8a`!

**Comment by rebello95** [comment]
Nice! Looks like our Linux CI uses `clang-8`, so your fix makes sense: https://github.com/lyft/envoy-mobile/blob/3bd4282d2ea1a2a976dd59ffee90aede38c750a5/ci/linux_ci_setup.sh#L28

Glad you got it fixed - closing out this issue since it's resolved.
